
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Home extends javax.swing.JFrame {

    
    public Home()    {
        /*RandomAccessFile quizFile = new RandomAccessFile("quiz.dat","rw");
        RandomAccessFile idsFile = new RandomAccessFile("ids.dat","rw");
        //quizFile.setLength(6864);
        System.out.println(quizFile.length());
        //idsFile.setLength(12);
        System.out.println(idsFile.length());*/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        adminButton = new javax.swing.JMenu();
        adminLogin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        teacherLogin = new javax.swing.JMenuItem();
        teacherSignup = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        studentLogin = new javax.swing.JMenuItem();
        studentSignup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem.png"))); // NOI18N

        adminButton.setText("Admin");

        adminLogin.setText("Admin Login");
        adminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginActionPerformed(evt);
            }
        });
        adminButton.add(adminLogin);

        jMenuBar1.add(adminButton);

        jMenu2.setText("Teacher");

        teacherLogin.setText("Teacher Login");
        teacherLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherLoginActionPerformed(evt);
            }
        });
        jMenu2.add(teacherLogin);

        teacherSignup.setText("Teacher Signup");
        teacherSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherSignupActionPerformed(evt);
            }
        });
        jMenu2.add(teacherSignup);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Student");

        studentLogin.setText("Student Login");
        studentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLoginActionPerformed(evt);
            }
        });
        jMenu3.add(studentLogin);

        studentSignup.setText("Student Signup");
        studentSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSignupActionPerformed(evt);
            }
        });
        jMenu3.add(studentSignup);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherLoginActionPerformed
        new teacherLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_teacherLoginActionPerformed

    private void teacherSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherSignupActionPerformed
        new teacherSignup().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_teacherSignupActionPerformed

    private void adminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginActionPerformed
        new AdminLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminLoginActionPerformed

    private void studentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLoginActionPerformed
        new studentLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studentLoginActionPerformed

    private void studentSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSignupActionPerformed
        new studentSignup().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studentSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home h;
               
                   h = new Home();
                    h.setVisible(true);
               
                    
               
                    
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminButton;
    private javax.swing.JMenuItem adminLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem studentLogin;
    private javax.swing.JMenuItem studentSignup;
    private javax.swing.JMenuItem teacherLogin;
    private javax.swing.JMenuItem teacherSignup;
    // End of variables declaration//GEN-END:variables
}
