
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class StudentPanel extends javax.swing.JFrame {

    /**
     * Creates new form TeacherPanel
     */
    public StudentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentRegButton = new javax.swing.JButton();
        attemptQuizButton = new javax.swing.JButton();
        logoutButtton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentRegButton.setText("View Student Registrations");
        studentRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRegButtonActionPerformed(evt);
            }
        });

        attemptQuizButton.setText("View All Quizzes");
        attemptQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptQuizButtonActionPerformed(evt);
            }
        });

        logoutButtton.setBackground(new java.awt.Color(255, 0, 51));
        logoutButtton.setText("Logout");
        logoutButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButttonActionPerformed(evt);
            }
        });

        searchButton.setText("Search Quiz");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Student");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(logoutButtton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attemptQuizButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentRegButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(studentRegButton)
                .addGap(18, 18, 18)
                .addComponent(attemptQuizButton)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(logoutButtton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attemptQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptQuizButtonActionPerformed

        try {
            new viewQuizzes().setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_attemptQuizButtonActionPerformed

    private void logoutButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButttonActionPerformed
        new studentLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButttonActionPerformed

    private void studentRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRegButtonActionPerformed
        try {
            new stiudentRegs().setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(TeacherPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentRegButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
       
        
        String s = JOptionPane.showInputDialog("Enter Quiz Topic to search","");
        try {
            Quizzes q = new Quizzes();
            RandomAccessFile quizFile = new RandomAccessFile("quiz.dat","rw");
            RandomAccessFile idsFile = new RandomAccessFile("ids.dat","rw");
            int n = (int) idsFile.length()/4 ;
            Boolean found = false;
            for(int i = 0; i < n; i++) {
                q.read();
                if(q.getTopic().toLowerCase().contains(s.toLowerCase())) {
                    found = true;
                    int dialogresult = JOptionPane.showConfirmDialog(null, " Quiz Found \n\n QuizID: " + q.getId() + "\n Quiz Subject: " + q.getSubject() + "\n Quiz Topic: " + q.getTopic() + "\n Total Questions: " + q.getTotalQs() + "\n\n Do you want to attempt this Quiz?","Warning",JOptionPane.YES_NO_OPTION);
                    if(dialogresult == JOptionPane.YES_NO_OPTION) {
                        new startQuiz(q.getId()).setVisible(true);
                        this.setVisible(false);
                    }
                    
                }
                
                //System.out.println(q.getTopic());
                //break;
            }
            if(found == false) {
                    JOptionPane.showMessageDialog(this, "No Quiz found on this topic, View all quizzes to access all quizzes");
                    
                
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attemptQuizButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButtton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton studentRegButton;
    // End of variables declaration//GEN-END:variables
}
